"""Subscriber freshness tools backed by RevenueCat overview polling and local webhook state."""

from __future__ import annotations

from typing import Any

from tooling import ToolDefinition


def refresh_subscriber_overview(runtime: Any, arguments: dict[str, Any]) -> dict[str, Any]:
    del arguments
    overview = runtime.revenuecat.get_overview()
    snapshot = None
    if overview is not None:
        snapshot = runtime.subscriber_store.record_overview_snapshot(overview)
    return {
        "ok": True,
        "overview": overview,
        "snapshot": snapshot,
        "snapshot_path": str(runtime.subscriber_store.snapshot_path),
    }


def get_subscriber_snapshot(runtime: Any, arguments: dict[str, Any]) -> dict[str, Any]:
    del arguments
    return {
        "ok": True,
        "snapshot": runtime.subscriber_store.get_snapshot(),
        "snapshot_path": str(runtime.subscriber_store.snapshot_path),
        "event_log_path": str(runtime.subscriber_store.event_log_path),
        "overview_history_path": str(runtime.subscriber_store.overview_history_path),
    }


def list_subscriber_events(runtime: Any, arguments: dict[str, Any]) -> dict[str, Any]:
    limit = int(arguments.get("limit") or 20)
    return {
        "ok": True,
        "limit": limit,
        "events": runtime.subscriber_store.list_recent_events(limit=limit),
        "event_log_path": str(runtime.subscriber_store.event_log_path),
    }


def list_subscriber_overview_history(runtime: Any, arguments: dict[str, Any]) -> dict[str, Any]:
    limit = int(arguments.get("limit") or 20)
    return {
        "ok": True,
        "limit": limit,
        "entries": runtime.subscriber_store.list_recent_overview_snapshots(limit=limit),
        "overview_history_path": str(runtime.subscriber_store.overview_history_path),
    }


SUBSCRIBER_TOOLS = [
    ToolDefinition(
        name="refresh_subscriber_overview",
        description="Fetch the latest RevenueCat overview metrics and persist a local subscriber snapshot.",
        input_schema={"type": "object", "properties": {}, "additionalProperties": False},
        handler=refresh_subscriber_overview,
    ),
    ToolDefinition(
        name="get_subscriber_snapshot",
        description="Read the local subscriber freshness snapshot generated by polling and webhook ingestion.",
        input_schema={"type": "object", "properties": {}, "additionalProperties": False},
        handler=get_subscriber_snapshot,
    ),
    ToolDefinition(
        name="list_subscriber_events",
        description="Read recent RevenueCat webhook events stored in the local event log.",
        input_schema={
            "type": "object",
            "properties": {
                "limit": {"type": "integer", "minimum": 1, "maximum": 200},
            },
            "additionalProperties": False,
        },
        handler=list_subscriber_events,
    ),
    ToolDefinition(
        name="list_subscriber_overview_history",
        description="Read recent append-only RevenueCat overview snapshots stored by the local freshness layer.",
        input_schema={
            "type": "object",
            "properties": {
                "limit": {"type": "integer", "minimum": 1, "maximum": 200},
            },
            "additionalProperties": False,
        },
        handler=list_subscriber_overview_history,
    ),
]
